
CREATE TABLE CARS
(
  MODEL_YEARS     INTEGER     NOT NULL COMMENT '연식',
  MODEL_CODE_ID   VARCHAR(50) NOT NULL COMMENT '차종_ID',
  COMPANY_CODE_ID VARCHAR(50) NOT NULL COMMENT '회사_ID',
  CARS_ID         VARCHAR(50) NOT NULL COMMENT '유니크_ID',
  PRIMARY KEY (CARS_ID)
) COMMENT '자동차';

CREATE TABLE CARS_OPTION
(
  CARS_OPTION    VARCHAR(50) NOT NULL COMMENT '차옵션',
  CARS_OPTION_ID VARCHAR(50) NOT NULL COMMENT '차 옵션 ID',
  PRIMARY KEY (CARS_OPTION_ID)
) COMMENT '차 옵션';

CREATE TABLE COMPANY
(
  COMPANY         VARCHAR(50) NOT NULL COMMENT '회사',
  COMPANY_CODE_ID VARCHAR(50) NOT NULL COMMENT '회사_ID',
  PRIMARY KEY (COMPANY_CODE_ID)
) COMMENT '회사이름';

CREATE TABLE CONNECT
(
  CARS_OPTION_ID VARCHAR(50) NOT NULL COMMENT '차 옵션 ID',
  CARS_ID        VARCHAR(50) NOT NULL COMMENT '유니크_ID'
) COMMENT '연결테이블';

CREATE TABLE MODEL
(
  MODEL         VARCHAR(50) NOT NULL COMMENT '차 종',
  MODEL_CODE_ID VARCHAR(50) NOT NULL COMMENT '차종_ID',
  PRIMARY KEY (MODEL_CODE_ID)
) COMMENT '차종';

ALTER TABLE CONNECT
  ADD CONSTRAINT FK_CARS_OPTION_TO_CONNECT
    FOREIGN KEY (CARS_OPTION_ID)
    REFERENCES CARS_OPTION (CARS_OPTION_ID);

ALTER TABLE CARS
  ADD CONSTRAINT FK_MODEL_TO_CARS
    FOREIGN KEY (MODEL_CODE_ID)
    REFERENCES MODEL (MODEL_CODE_ID);

ALTER TABLE CARS
  ADD CONSTRAINT FK_COMPANY_TO_CARS
    FOREIGN KEY (COMPANY_CODE_ID)
    REFERENCES COMPANY (COMPANY_CODE_ID);

ALTER TABLE CONNECT
  ADD CONSTRAINT FK_CARS_TO_CONNECT
    FOREIGN KEY (CARS_ID)
    REFERENCES CARS (CARS_ID);
