
CREATE TABLE ADDRESS_CODE
(
  ADDRESS      VARCHAR(500) NOT NULL COMMENT '주소',
  ADDERSS_CODE VARCHAR(50)  NOT NULL COMMENT '주소_ ID',
  PRIMARY KEY (ADDERSS_CODE)
) COMMENT '주소';

CREATE TABLE GENDER_CODE
(
  GENDER      VARCHAR     NOT NULL COMMENT '성별',
  GENDER_CODE VARCHAR(50) NOT NULL,
  PRIMARY KEY (GENDER_CODE)
) COMMENT '성별코드';

CREATE TABLE HOBBY_CODE
(
  HOBBY         VARCHAR(50) NOT NULL COMMENT '취미',
  HOBBY_CODE_ID VARCHAR(50) NOT NULL COMMENT '유니크 ID',
  PRIMARY KEY (HOBBY_CODE_ID)
) COMMENT '취미코드';

CREATE TABLE MEMBERS
(
  NAME         VARCHAR(50) NOT NULL COMMENT '이름',
  AGE          INTEGER     NOT NULL COMMENT '나이',
  TELEPHONE    VARCHAR(50) NOT NULL COMMENT '전화번호',
  MEMBERS_ID   VARCHAR(50) NOT NULL COMMENT '유니크 ID',
  ADDRESS      VARCHAR(50) NOT NULL COMMENT '주소',
  GENDER_CODE  VARCHAR(50) NOT NULL COMMENT '성별ID',
  ADDERSS_CODE VARCHAR(50) NOT NULL COMMENT '주소_ ID',
  PRIMARY KEY (MEMBERS_ID)
);

CREATE TABLE MEMBERS_HOBBY 
(
  HOBBY_CODE_ID VARCHAR(50) NOT NULL COMMENT '유니크 ID',
  MEMBERS_ID    VARCHAR(50) NOT NULL COMMENT '유니크 ID'
) COMMENT '회원 _취미';

CREATE TABLE MEMBERS_LOGIN
(
  EMAIL      VARCHAR(50) NOT NULL COMMENT '이메일',
  MEMBERS_ID VARCHAR(50) NOT NULL COMMENT '유니크 ID'
);

ALTER TABLE MEMBERS_LOGIN
  ADD CONSTRAINT FK_MEMBERS_TO_MEMBERS_LOGIN
    FOREIGN KEY (MEMBERS_ID)
    REFERENCES MEMBERS (MEMBERS_ID);

ALTER TABLE MEMBERS_HOBBY 
  ADD CONSTRAINT FK_HOBBY_CODE_TO_MEMBERS_HOBBY 
    FOREIGN KEY (HOBBY_CODE_ID)
    REFERENCES HOBBY_CODE (HOBBY_CODE_ID);

ALTER TABLE MEMBERS_HOBBY 
  ADD CONSTRAINT FK_MEMBERS_TO_MEMBERS_HOBBY 
    FOREIGN KEY (MEMBERS_ID)
    REFERENCES MEMBERS (MEMBERS_ID);

ALTER TABLE MEMBERS
  ADD CONSTRAINT FK_GENDER_CODE_TO_MEMBERS
    FOREIGN KEY (GENDER_CODE)
    REFERENCES GENDER_CODE (GENDER_CODE);

ALTER TABLE MEMBERS
  ADD CONSTRAINT FK_ADDRESS_CODE_TO_MEMBERS
    FOREIGN KEY (ADDERSS_CODE)
    REFERENCES ADDRESS_CODE (ADDERSS_CODE);
