SELECT  MAX(REPY.CNT) AS MAX, REPY.NAME
FROM
(
SELECT ORD.EmployeeID, COUNT(ORD.EmployeeID) AS CNT, EPY.LastName AS NAME
FROM Orders AS ORD
JOIN Employees AS EPY
ON ORD.EmployeeID = EPY.EmployeeID
GROUP BY ORD.EmployeeID
) AS REPY